export const MARK_A_NOTIFICATION_AS_READ = "MARK_A_NOTIFICATION_AS_READ";
export const BLOCK_A_TYPE_OF_NOTIFICATIONS_BY_USER =
  "BLOCK_A_TYPE_OF_NOTIFICATIONS_BY_USER";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";
