export const UPDATE_DEFAULT_ANALYSIS_LIST = "UPDATE_DEFAULT_ANALYSIS_LIST";
export const UPDATE_HOT_ANALYSIS_LIST = "UPDATE_HOT_ANALYSIS_LIST";
export const UPDATE_PICKS_ANALYSIS_LIST = "UPDATE_PICKS_ANALYSIS_LIST";

export const LIKE_AN_ANALYSIS = "LIKE_AN_ANALYSIS";
export const DISLIKE_AN_ANALYSIS = "DISLIKE_AN_ANALYSIS";

export const REPLY_AN_ANALYSIS = "REPLY_AN_ANALYSIS";
export const SHARE_AN_ANALYSIS = "SHARE_AN_ANALYSIS";

export const FAVOURITE_AN_ANALYSIS = "FAVOURITE_AN_ANALYSIS";
export const UN_FAVOURITE_AN_ANALYSIS = "UN_FAVOURITE_AN_ANALYSIS";

export const UPDATE_ANALYSES = "UPDATE_ANALYSES";
export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
export const UPDATE_REPLIES = "UPDATE_REPLIES";

export const UPDATE_STRATEGIES_STATUS = "UPDATE_STRATEGIES_STATUS";

export const INIT_MIXEDCONTENT = "INIT_MIXEDCONTENT";
export const UPDATE_MIXEDCONTENT = "UPDATE_MIXEDCONTENT";
