export const UPDATE_SEARCH_ANALYSES = "UPDATE_SEARCH_ANALYSES";
export const UPDATE_SEARCH_PROFILE_ANALYSES = "UPDATE_SEARCH_PROFILE_ANALYSES";
export const UPDATE_FAVORITE_PROFILE_ANALYSES = "UPDATE_FAVORITE_PROFILE_ANALYSES";
