export const UPDATE_FLOATAPP_SELF_ANALYSES = "UPDATE_FLOATAPP_SELF_ANALYSES";
export const UPDATE_FLOATAPP_SELF_MOST_SHARED_ANALYSES =
  "UPDATE_FLOATAPP_SELF_MOST_SHARED_ANALYSES";
export const UPDATE_FLOATAPP_SELF_MOST_LIKED_ANALYSES =
  "UPDATE_FLOATAPP_SELF_MOST_LIKED_ANALYSES";
export const UPDATE_FLOATAPP_SELF_MOST_VIEW_ANALYSES =
  "UPDATE_FLOATAPP_SELF_MOST_VIEW_ANALYSES";
export const UPDATE_FLOATAPP_SELF_MOST_FAVORITE_ANALYSES =
  "UPDATE_FLOATAPP_SELF_MOST_FAVORITE_ANALYSES";
export const UPDATE_FLOATAPP_SELF_MOST_COMMENT_ANALYSES =
  "UPDATE_FLOATAPP_SELF_MOST_COMMENT_ANALYSES";
export const UPDATE_FLOATAPP_SELF_LATEST_UPDATED_ANALYSES =
  "UPDATE_FLOATAPP_SELF_LATEST_UPDATED_ANALYSES";
export const UPDATE_FLOATAPP_SELF_ANALYSES_BY_DATE =
  "UPDATE_FLOATAPP_SELF_ANALYSES_BY_DATE";
