export const UPDATE_SETTING_PHRASE = "UPDATE_SETTING_PHRASE";
export const BASIC_SETTING_PHRASE = "BASIC_SETTING_PHRASE";
export const FAVOURITES_SETTING_PHRASE = "FAVOURITES_SETTING_PHRASE";
export const NOT_IN_SETTING_PHRASE = "NOT_IN_SETTING_PHRASE";
